let User,CustomErrorHandler;_a33‍.x([["default",()=>_a33‍.o]]);_a33‍.w("../../models",[["User",["User"],function(v){User=v}]]);_a33‍.w("../../services/CustomErrorHandler",[["default",["CustomErrorHandler"],function(v){CustomErrorHandler=v}]]);


const userController = {
  async me(req,res,next){
      try {
          const user = await User.findOne({_id:req.user._id});
          if(!user){
            return next(CustomErrorHandler.notFound());
          }
          res.json(user);
      } catch (err) {
          return next(err);
      }
  }
};

_a33‍.d(userController);